version: '3'
services:
  notebook:
    build: .
    container_name: udacity
    ports:
      - '8888:8888'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./opt:/home/jovyan/opt
      - ./data:/home/jovyan/data
      - ./src:/home/jovyan/src
      - ./notebooks:/home/jovyan/notebooks
    command: start-notebook.sh --NotebookApp.token=''